name: Nightly Smoke test

on:
  workflow_dispatch:
    inputs:
      project:
        description: "Playwright project to use"
        default: replay-chromium
  schedule:
    - cron:  '30 5 * * *'

jobs:
  smoke-test:
    # if: github.repository == 'redwoodjs/redwood'
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        node-version: ['14', '16']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} | Node ${{ matrix.node-version }} latest
    env:
      REDWOOD_CI: 1
      REDWOOD_VERBOSE_TELEMETRY: 1
      PLAYWRIGHT_BROWSERS_PATH: 0 # this makes sure that playwright dependencies are cached in node_modules
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Get yarn cache directory path
      #   id: yarn-cache-dir-path
      #   run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      # - name: Cache yarn
      #   uses: actions/cache@v2
      #   id: yarn-cache
      #   with:
      #     path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      #     key: yarn-${{ hashFiles('yarn.lock') }}
      #     restore-keys: |
      #       yarn-

      - name: Install framework dependencies
        run: |
          yarn install --immutable

      - name: Setup test project
        id: setup_test_project
        uses: ./.github/actions/setup_test_project
        env:
          REDWOOD_DISABLE_TELEMETRY: 1

      - name: Install Playwright deps
        run: npx playwright install --with-deps chromium

      - name: Run `rw build` without prerender
        run: |
          yarn rw build --no-prerender
        working-directory: ${{ steps.setup_test_project.outputs.test_project_path }}

      - name: Run smoke tests on 'rw dev' and 'rw serve'
        uses: replayio/action-playwright@main
        with:
<<<<<<< HEAD
          project: ${{ inputs.project || 'replay-firefox' }}
          working-directory: ./tasks/smoke-test
          issue-number: ${{ github.event.pull_request.number }}
          apiKey: ${{ secrets.RECORD_REPLAY_API_KEY }}
=======
          project: ${{ inputs.project }}
          working-directory: ./tasks/smoke-test
          issue-number: ${{ github.event.pull_request.number }}
          apiKey: ${{ secrets.RECORD_REPLAY_API_KEY }}
          upload-all: true
>>>>>>> origin/main
        env:
          PROJECT_PATH: ${{ steps.setup_test_project.outputs.test_project_path }}
          REDWOOD_DISABLE_TELEMETRY: 1
